# Generated by Django 4.2.3 on 2024-09-27 12:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_at_timestamp", models.IntegerField(editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_at_timestamp", models.IntegerField(editable=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at_timestamp", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
